using System.Collections.Concurrent;
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace KitchenServer.Web.Services;

/// <summary>
/// One open editor tab: the per-refresh <see cref="TabKey"/> the user copies to
/// the agent, plus the live browser WebSocket that reaches the Unity client. The
/// MCP layer forwards a command through <see cref="SendCommandAsync"/> and the
/// browser's reply is matched back by request id via <see cref="ResolveResponse"/>.
/// </summary>
public class McpSession
{
    private readonly object _lock = new();
    private readonly SemaphoreSlim _sendLock = new(1, 1);
    private readonly ConcurrentDictionary<string, TaskCompletionSource<JsonElement>> _pending = new();

    private WebSocket? _browserWebSocket;
    private DateTime _lastActivity = DateTime.UtcNow;
    private int _requestCounter;

    /// <summary>Ephemeral key generated by the editor tab on every load. Bearer secret for THIS tab.</summary>
    public string TabKey { get; init; } = Guid.NewGuid().ToString("N");
    public string UserId { get; init; } = "";
    public string? ProjectId { get; init; }
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;
    public TimeSpan SessionTtl { get; set; } = TimeSpan.FromMinutes(30);

    public DateTime LastActivity { get { lock (_lock) return _lastActivity; } }

    public WebSocket? BrowserWebSocket
    {
        get { lock (_lock) return _browserWebSocket; }
        set { lock (_lock) _browserWebSocket = value; }
    }

    public bool IsBrowserConnected => BrowserWebSocket?.State == WebSocketState.Open;

    /// <summary>True while at least one authenticated agent is bound to this tab (drives the green light).</summary>
    public bool AgentBound { get; set; }

    /// <summary>True when another tab has taken over the project lock — changes in this tab will not be saved.</summary>
    public bool LockLost { get; set; }

    public string SessionId => TabKey;
    public bool IsActive => IsBrowserConnected;
    public string AccessKey => TabKey;

    public void Touch() { lock (_lock) _lastActivity = DateTime.UtcNow; }

    /// <summary>
    /// Send an MCP command to the Unity client and await its reply. Returns the raw
    /// response envelope {id, type, data, etag}. Throws when the browser is not
    /// connected, on timeout, or if the socket drops mid-flight.
    /// </summary>
    public async Task<JsonElement> SendCommandAsync(string method, JsonObject? parameters,
        TimeSpan timeout, CancellationToken ct)
    {
        if (!IsBrowserConnected)
            throw new McpBridgeException(
                "Kitchen client is not connected. Open the project in the browser (or desktop app) and retry.");

        var id = $"srv-{Interlocked.Increment(ref _requestCounter)}";
        var envelope = new JsonObject
        {
            ["id"] = id,
            ["method"] = method,
            ["params"] = parameters ?? new JsonObject(),
        };
        var wire = envelope.ToJsonString();

        var tcs = new TaskCompletionSource<JsonElement>(TaskCreationOptions.RunContinuationsAsynchronously);
        _pending[id] = tcs;
        Touch();

        try
        {
            if (!await SendToBrowserAsync(wire, ct))
                throw new McpBridgeException(
                    "Kitchen client is not connected. Open the project in the browser (or desktop app) and retry.");

            using var timeoutCts = CancellationTokenSource.CreateLinkedTokenSource(ct);
            timeoutCts.CancelAfter(timeout);
            await using var _ = timeoutCts.Token.Register(() =>
                tcs.TrySetException(new McpBridgeException(
                    $"Timeout after {timeout.TotalSeconds:0}s waiting for \"{method}\". Is the app running and not frozen?")));

            return await tcs.Task;
        }
        finally
        {
            _pending.TryRemove(id, out _);
        }
    }

    /// <summary>Match a browser reply back to its pending request by id.</summary>
    public void ResolveResponse(string id, JsonElement response)
    {
        Touch();
        if (_pending.TryRemove(id, out var tcs))
            tcs.TrySetResult(response);
    }

    /// <summary>Fault every in-flight request (browser dropped / session closing).</summary>
    public void FailAllPending(string reason)
    {
        foreach (var kv in _pending)
            if (_pending.TryRemove(kv.Key, out var tcs))
                tcs.TrySetException(new McpBridgeException(reason));
    }

    /// <summary>Serialized send: a WebSocket allows only one outstanding SendAsync.</summary>
    public async Task<bool> SendToBrowserAsync(string json, CancellationToken ct)
    {
        var ws = BrowserWebSocket;
        if (ws is null || ws.State != WebSocketState.Open) return false;

        var data = Encoding.UTF8.GetBytes(json);
        await _sendLock.WaitAsync(ct);
        try
        {
            if (ws.State != WebSocketState.Open) return false;
            await ws.SendAsync(new ArraySegment<byte>(data), WebSocketMessageType.Text, true, ct);
            return true;
        }
        finally
        {
            _sendLock.Release();
        }
    }
}

/// <summary>A forwarded MCP command failed at the bridge (not a Unity domain error).</summary>
public sealed class McpBridgeException : Exception
{
    public McpBridgeException(string message) : base(message) { }
}
