using System;
using System.Collections.Generic;
using System.Linq;

/// <summary>
/// Русские литералы, которым МОЖНО остаться в коде, — поимённо и с причиной. Запись без
/// причины через полгода неотличима от недосмотра, поэтому причина обязательна, а
/// <see cref="LocalizationGuardTests.EveryAllowListEntry_StillMatchesSomething"/> снимает
/// запись, пережившую свой литерал.
/// </summary>
public static class LocalizationAllowList
{
    private const string Dev = "инструмент разработчика: виден только в тестах, журнале или служебной истории отмены, не в интерфейсе";
    private const string Log = "строка журнала для разработчика";
    private const string Identifier = "данные, а не подпись: имя узла / ключ сравнения / значение из файла";
    private const string Attribute = "причина [NotUndoable] — документация для разработчика";

    public static readonly IReadOnlyDictionary<string, string> Files = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Core/Diagnostics/PerfMonitor.cs"] = "оверлей F9 (замеры кадра) — инструмент разработчика",
        ["Core/Elements/DrawerValidator.cs"] = "ошибки ящика уходят только в ответ MCP (drawer_invalid)",
        ["Core/MCP/Contract/McpGuideTexts.cs"] = "справка MCP для ИИ-агента",
        ["Core/MCP/Contract/McpToolParams.cs"] = "описание параметров MCP для ИИ-агента",
        ["Core/MCP/Contract/McpToolRegistry.cs"] = "описание инструментов MCP для ИИ-агента",
        ["Core/MCP/McpWireEnums.cs"] = "русские синонимы значений во ВХОДЕ MCP — данные протокола",
        ["Core/Pure/Diagnostics/ListenerCostLog.cs"] = "журнал замеров для разработчика",
        ["Core/Pure/Diagnostics/NamedTally.cs"] = "журнал замеров для разработчика",
        ["Core/Pure/Diagnostics/SceneScanLog.cs"] = "журнал замеров для разработчика",
        ["Core/Pure/Diagnostics/SelectionWorkLog.cs"] = "журнал замеров для разработчика",
        ["Core/Pure/Elements/CoplanarSurfaceDetector.cs"] = "диагностика, которую читают только тесты",
        ["Core/Pure/UI/ConsoleLog.cs"] = "консоль разработчика (клавиша «ё»)",
        ["Core/Pure/UI/ContentExtent.cs"] = "диагностика раскладки для тестов",
        ["Core/Snap/SnapSystem.cs"] = "вердикты Diagnose читает только MCP-инструмент snap_diagnose",
        ["Tests/UiNodeOverlap.cs"] = "инфраструктура тестов снимков UI",
        ["Tests/UiSnapshotEngine.cs"] = "инфраструктура тестов снимков UI",
    };

    public static readonly IReadOnlyList<(string file, string fragment, string reason)> Literals =
        new List<(string, string, string)>
        {
            ("Core/Analysis/SceneAnalyzer.cs", "мс", Dev),
            ("Core/Analysis/SceneAnalyzer.cs", "мс×", Dev),
            ("Core/Commands/CreateLevelCommand.cs", "Добавить уровень «{_created.name}»", Dev),
            ("Core/Commands/DeleteLevelCommand.cs", "Удалить уровень «{_removed.name}»", Dev),
            ("Core/Commands/DeleteLevelCommand.cs", "Удалить уровень «{_removed.name}» ({_elementDele", Dev),
            ("Core/Commands/MoveToLevelCommand.cs", "Переместить на другой уровень", Dev),
            ("Core/Commands/RenameLevelCommand.cs", "Переименовать уровень «{_before}» в «{_after}»", Dev),
            ("Core/Commands/SetLevelElevationCommand.cs", "Отметка уровня «{_level.name}»", Dev),
            ("Core/Commands/SetLevelHeightCommand.cs", "Высота уровня «{_level.name}»", Dev),
            ("Core/Commands/WallLayerRehostCommand.cs", "Перепривязка {_layer.PartName}", Dev),
            ("Core/Elements/AssembledFacadeElement.cs", "собранный фасад плоский: рамка и заполнение видн", Dev),
            ("Core/Elements/BathMixerElement.cs", "излив и рычаг — части корпуса смесителя, отдельн", Dev),
            ("Core/Elements/BathtubElement.cs", "ванна — чаша с бортом по кругу, лицевой детали у", Dev),
            ("Core/Elements/BedElement.cs", "кровать смотрит вверх: матрас и подушки видны с ", Dev),
            ("Core/Elements/ChairElement.cs", "лицо стула — сиденье, оно часть корневого меша и", Dev),
            ("Core/Elements/CladdingElement.cs", "облицовка идёт по всей грани стены — лицевой дет", Dev),
            ("Core/Elements/CooktopElement.cs", "деталь не годится под варочную", Dev),
            ("Core/Elements/CooktopElement.cs", "лицо варочной — её верх: конфорки и обод видны с", Dev),
            ("Core/Elements/DecorSlots.cs", "декор ставится через SetMaterialCommand (Materia", Attribute),
            ("Core/Elements/DecorSlots.cs", "псевдоним PrimaryMaterialId — см. его причину", Attribute),
            ("Core/Elements/DoorElement.cs", "дверь — полотно в проёме: обе её стороны одинако", Dev),
            ("Core/Elements/DrawerElement.cs", "ящик снимают выдвинутым: короб виден целиком, ли", Dev),
            ("Core/Elements/DrawerMesh.cs", "Боковина L", Identifier),
            ("Core/Elements/DrawerMesh.cs", "Боковина R", Identifier),
            ("Core/Elements/DrawerMesh.cs", "Дно", Identifier),
            ("Core/Elements/DrawerMesh.cs", "Задник", Identifier),
            ("Core/Elements/DuctElement.cs", "воздуховод — тело без выделенной грани", Dev),
            ("Core/Elements/FacadeElement.cs", "фасад — плита: обе стороны одинаковы", Dev),
            ("Core/Elements/FenceElement.cs", "профилированный лист симметричен по толщине: у з", Dev),
            ("Core/Elements/FloorElement.cs", "пол горизонтален: его поверхность видна сверху с", Dev),
            ("Core/Elements/FloorSlabElement.cs", "плита перекрытия горизонтальна: у неё нет одной ", Dev),
            ("Core/Elements/FoundationElement.cs", "лента идёт по всему периметру несущих стен: у не", Dev),
            ("Core/Elements/GrilleElement.cs", "вентиляционная решётка — плоская накладка без вы", Dev),
            ("Core/Elements/InsulationElement.cs", "утеплитель идёт по всей грани стены под облицовк", Dev),
            ("Core/Elements/KitchenElement.cs", "{_data.PartName} ({_data.DimensionsMM.x}x{_data.", Dev),
            ("Core/Elements/KitchenElement.cs", "доска — коробка с кромкой: с любой стороны одна ", Dev),
            ("Core/Elements/LightSourceElement.cs", "светильник — шар: он одинаков со всех сторон", Dev),
            ("Core/Elements/PanelElement.cs", "панель — плита: обе стороны одинаковы", Dev),
            ("Core/Elements/PartCutoutElement.cs", "height={height:F1}мм ({Mount.DescribeCatchBand()", Dev),
            ("Core/Elements/PartData.cs", "{_partName} ({_dimensionsMM.x}x{_dimensionsMM.y}", Dev),
            ("Core/Elements/PartMount.cs", "полоса {-_releaseMM}..{_catchMM}", Dev),
            ("Core/Elements/PillarElement.cs", "опора — тело вращения: она одинакова со всех сто", Dev),
            ("Core/Elements/PipeCapElement.cs", "заглушка — тело вращения", Dev),
            ("Core/Elements/PipeCouplingElement.cs", "муфта — тело вращения", Dev),
            ("Core/Elements/PipeElbowElement.cs", "отвод — два цилиндра под углом, лицевой детали н", Dev),
            ("Core/Elements/PipeElement.cs", "труба — тело вращения", Dev),
            ("Core/Elements/PipeEndFittings.cs", "Порт {owner.PartName}", Dev),
            ("Core/Elements/PipeReturnElement.cs", "обратка — тело вращения", Dev),
            ("Core/Elements/PipeSupplyElement.cs", "подача — тело вращения", Dev),
            ("Core/Elements/PipeTeeElement.cs", "тройник — три цилиндра, лицевой детали нет", Dev),
            ("Core/Elements/PouffeElement.cs", "пуф — тумба с сиденьем сверху, лицевой детали у ", Dev),
            ("Core/Elements/RadialShelfElement.cs", "радиусная полка — сектор плиты, лицевой детали н", Dev),
            ("Core/Elements/RadiusTableElement.cs", "стол — столешница на ногах: лицевой детали у нег", Dev),
            ("Core/Elements/RoofElement.cs", "крыша — несколько скатов вокруг конька: у неё не", Dev),
            ("Core/Elements/ScrewLegElement.cs", "винтовая опора — тело вращения", Dev),
            ("Core/Elements/ShowerColumnElement.cs", "гусак и лейка — части корпуса стойки, отдельной ", Dev),
            ("Core/Elements/SinkElement.cs", "деталь не годится под мойку", Dev),
            ("Core/Elements/SinkElement.cs", "мойка смотрит вверх: чаша видна сверху с любой с", Dev),
            ("Core/Elements/SofaElement.cs", "подушки дивана стоят между подлокотниками: ни од", Dev),
            ("Core/Elements/StoolElement.cs", "табурет — сиденье на ногах, лицевой детали у нег", Dev),
            ("Core/Elements/TableElement.cs", "стол — столешница на ногах: лицевой детали у нег", Dev),
            ("Core/Elements/ToiletElement.cs", "чаша и крышка видны и поверх бачка: защищённой л", Dev),
            ("Core/Elements/VentGapElement.cs", "обрешётка вентзазора идёт по всей грани стены — ", Dev),
            ("Core/Elements/WallHungToiletElement.cs", "чаша и крышка подвесного унитаза видны и со стор", Dev),
            ("Core/Elements/WallLayerElement.cs", "слой идёт по всей грани стены: у него нет одной ", Dev),
            ("Core/Elements/WindowElement.cs", "окно — створка в проёме: обе её стороны одинаков", Dev),
            ("Core/Geometry/EdgeDetents.cs", "кромка+", Log),
            ("Core/Geometry/EdgeDetents.cs", "кромка-", Log),
            ("Core/Geometry/EdgeDetents.cs", "от кромки", Log),
            ("Core/Geometry/EdgeDetents.cs", "паз+", Log),
            ("Core/Geometry/EdgeDetents.cs", "паз-", Log),
            ("Core/Geometry/EdgeDetents.cs", "своб", Log),
            ("Core/Geometry/EdgeDetents.cs", "центр", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "du={offer.du * 1000f:F2}мм dv={offer.dv * 1000f:", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "выравнивание по дальней кромке m{i}/o{j} ", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "грань m{i}/o{j} зазор={offer.planeDist * 1000f:F", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "оси[u:{offer.detentU} v:{offer.detentV}] ", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "оси[u:{offer.detentU} v:{offer.detentV}] → ", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "перекр={offer.overlapRatio:P0} ", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "поз {offer.snapPos.x:F3},{offer.snapPos.y:F3},{o", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "посадка под деталью m{i}/o{j} ", Log),
            ("Core/Geometry/SnapCandidateCollector.cs", "сдвиг={offer.shift * 1000f:F2}мм", Log),
            ("Core/Geometry/SnapCore.cs", "[Snap] → {seat.targetName} | устье {seat.movedPo", Log),
            ("Core/Geometry/SnapCore.cs", "встречные={(seat.opposed ? ", Log),
            ("Core/Geometry/SnapCore.cs", "сдвиг={seat.delta.magnitude / AppConstants.MM_TO", Log),
            ("Core/Infrastructure/EditModeManager.cs", "Короб", Identifier),
            ("Core/Lighting/LightPickRenderer.cs", "[LightPick] Шейдер Hidden/OverlayLine не найден ", Log),
            ("Core/Materials/EdgeSubstrate.cs", "Подложка торца", Identifier),
            ("Core/Materials/MaterialCatalog.cs", "ЛДСП", Identifier),
            ("Core/Materials/MaterialCatalog.cs", "Серый", Identifier),
            ("Core/Materials/TextureIndex.cs", "'{id}': tileWidthMM={e.tileWidthMM} — декор проп", Log),
            ("Core/Materials/TextureIndex.cs", "'{id}': цвет '{raw}' не разобран — взят цвет по ", Log),
            ("Core/Materials/TextureIndex.cs", "ЛДСП", Identifier),
            ("Core/Materials/TextureIndex.cs", "запись #{index}: id '{id}' уже встречался — деко", Log),
            ("Core/Materials/TextureIndex.cs", "запись #{index}: пустой id — декор пропущен", Log),
            ("Core/Materials/TextureIndex.cs", "запись #{index}: пустой объект", Log),
            ("Core/Materials/TextureIndex.cs", "индекс пуст", Log),
            ("Core/Materials/TextureIndex.cs", "не разобрать JSON: {e.Message}", Log),
            ("Core/Materials/TextureIndex.cs", "нет массива textures", Log),
            ("Core/Materials/TextureLibrary.cs", "{def.fileName}: не картинка или битый файл", Log),
            ("Core/Measure/MeasureRenderer.cs", "[Measure] Шейдер Hidden/OverlayLine не найден — ", Log),
            ("Core/Pure/Construction/FoundationLoosening.cs", "ЕНиР, сборник Е2 «Земляные работы», приложение (", Dev),
            ("Core/Pure/Construction/FoundationLoosening.cs", "— конкретные числа не сверены исполнителем, см. ", Dev),
            ("Core/Pure/Construction/FoundationRebarDefaults.cs", "(пункт не подтверждён исполнителем, см. Normativ", Dev),
            ("Core/Pure/Construction/FoundationRebarDefaults.cs", "СП 63.13330.2018, п. 10.3.2 — защитный слой при ", Dev),
            ("Core/Pure/Construction/FoundationSoleWidth.cs", "СП 22.13330.2016, конструктивный минимум ширины ", Dev),
            ("Core/Pure/Construction/FoundationSoleWidth.cs", "плюс запас на грунт (docs/NORMATIVE-DEFAULTS.md ", Dev),
            ("Core/Pure/Construction/FoundationSoleWidth.cs", "стены + 100-150 мм»; пункт не подтверждён исполн", Dev),
            ("Core/Pure/Construction/FrostDepth.cs", "СП 22.13330.2016, 5.5.3, формула (5.3)", Dev),
            ("Core/Pure/Construction/FrostDepth.cs", "СП 25.13330", Dev),
            ("Core/Pure/Construction/MasonryUnit.cs", "ГОСТ 31360-2024", Dev),
            ("Core/Pure/Construction/MasonryUnit.cs", "ГОСТ 530-2012", Dev),
            ("Core/Pure/Construction/MasonryUnit.cs", "ГОСТ 8486-86", Dev),
            ("Core/Pure/Construction/MasonryUnit.cs", "шаг утеплителя 600 мм", Dev),
            ("Core/Pure/Construction/RafterSectionTable.cs", "СП 64.13330.2017 «Деревянные конструкции», подбо", Dev),
            ("Core/Pure/Construction/RafterSectionTable.cs", "пролёту (пункт не подтверждён исполнителем — см.", Dev),
            ("Core/Pure/Construction/RegionClimate.cs", "СП 131.13330.2020, таблица 5.1", Dev),
            ("Core/Pure/Infrastructure/McpPortArgument.cs", " вне допустимого диапазона ", Log),
            ("Core/Pure/Infrastructure/McpPortArgument.cs", " ожидает номер порта, получено \\\"", Log),
            ("Core/Pure/Infrastructure/McpPortArgument.cs", " — использован порт по умолчанию ", Log),
            ("Core/Pure/Infrastructure/McpPortArgument.cs", "\\\" — использован порт по ", Log),
            ("Core/Pure/Infrastructure/McpPortArgument.cs", "умолчанию ", Log),
            ("Core/Pure/Infrastructure/McpSaveDirectoryArgument.cs", " ожидает путь к каталогу, получена пустая строка", Log),
            ("Core/Pure/Rendering/FrontFaceVisibility.cs", " — такой детали в сцене нет", Dev),
            ("Core/Pure/Update/UpdateCoordinator.cs", "[Update] загрузка не удалась: {reason}", Log),
            ("Core/Pure/Update/UpdateCoordinator.cs", "[Update] проверка не удалась: {reason}", Log),
            ("Core/Pure/Update/UpdateCoordinator.cs", "манифест не описывает устанавливаемый релиз: ", Log),
            ("Core/Pure/Update/UpdateCoordinator.cs", "сервер не вернул манифест", Log),
            ("Core/Rendering/HoverTint.cs", " не найден — подсветка ", Log),
            ("Core/Rendering/HoverTint.cs", "[HoverTint] Шейдер ", Log),
            ("Core/Rendering/HoverTint.cs", "детали, названной пунктом списка, не будет видна", Log),
            ("Core/Rendering/HoverTint.cs", "деталях, то есть отвечает не на тот вопрос, кото", Log),
            ("Core/Rendering/HoverTint.cs", "здесь нет намеренно: с честной проверкой глубины", Log),
            ("Core/Snap/Handles/HandleMaterials.cs", " не найден — ручки трансформации ", Log),
            ("Core/Snap/Handles/HandleMaterials.cs", "[Handles] Шейдер ", Log),
            ("Core/Snap/Handles/HandleMaterials.cs", "инструмент молча перестаёт работать.", Log),
            ("Core/Snap/Handles/HandleMaterials.cs", "не будут видны. Подмены обычным шейдером здесь н", Log),
            ("Core/Snap/Handles/HandleMaterials.cs", "с честной проверкой глубины ручка тонет в соседн", Log),
            ("Core/UI/BathMixerFieldsEditor.cs", "ВылетОтражателяСмесителя", Identifier),
            ("Core/UI/BathMixerFieldsEditor.cs", "ДиаметрКорпусаСмесителя", Identifier),
            ("Core/UI/BathMixerFieldsEditor.cs", "ДиаметрШтуцераСмесителя", Identifier),
            ("Core/UI/BathMixerFieldsEditor.cs", "ДлинаИзливаСмесителя", Identifier),
            ("Core/UI/BathMixerFieldsEditor.cs", "ДлинаКорпусаСмесителя", Identifier),
            ("Core/UI/BathMixerFieldsEditor.cs", "МежосевоеСмесителя", Identifier),
            ("Core/UI/BathtubFieldsEditor.cs", "БортВанны", Identifier),
            ("Core/UI/BathtubFieldsEditor.cs", "ГлубинаЧашиВанны", Identifier),
            ("Core/UI/BathtubFieldsEditor.cs", "РадиусЧашиВанны", Identifier),
            ("Core/UI/BathtubFieldsEditor.cs", "СкруглениеДнаВанны", Identifier),
            ("Core/UI/ChairFieldsEditor.cs", "ВысотаСиденья", Identifier),
            ("Core/UI/ChairFieldsEditor.cs", "СкруглениеСтула", Identifier),
            ("Core/UI/ChoiceRowUndo.cs", "Свойства ", Dev),
            ("Core/UI/ContextMenuRowFactory.cs", "F_Название", Identifier),
            ("Core/UI/ContextMenuRowFactory.cs", "L_Название", Identifier),
            ("Core/UI/ContextMenuUI.cs", "Поворот ", Dev),
            ("Core/UI/ContextMenuUI.cs", "Свойства {target.PartName}", Dev),
            ("Core/UI/LevelsWindowUI.cs", "Добавить уровень «{next.name}»", Dev),
            ("Core/UI/PouffeFieldsEditor.cs", "СидушкаПуфика", Identifier),
            ("Core/UI/PouffeFieldsEditor.cs", "СкруглениеПуфика", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ВылетСтойкиОтСтены", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ВыносГусакаСтойки", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ВысотаДушевойСтойки", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ДиаметрЛейкиСтойки", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ДиаметрРучнойЛейки", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ДиаметрШтангиСтойки", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ДлинаШлангаСтойки", Identifier),
            ("Core/UI/ShowerColumnFieldsEditor.cs", "ТолщинаЛейкиСтойки", Identifier),
            ("Core/UI/SofaFieldsEditor.cs", "ВысотаОснованияДивана", Identifier),
            ("Core/UI/SofaFieldsEditor.cs", "СкруглениеДивана", Identifier),
            ("Core/UI/ToiletFieldsEditor.cs", "ВысотаПанелиСмыва", Identifier),
            ("Core/UI/ToiletFieldsEditor.cs", "ВысотаЧашиУнитаза", Identifier),
            ("Core/UI/WallDeviceFieldsEditor.cs", "ВыносОтСтены", Identifier),
            ("Core/UI/WallDeviceFieldsEditor.cs", "ВысотаРамки", Identifier),
            ("Core/UI/WallDeviceFieldsEditor.cs", "ШиринаРамки", Identifier),
            ("Core/UI/WallFieldsEditor.cs", "КладкаЗапас", Identifier),
            ("Core/UI/WallFieldsEditor.cs", "КладкаШов", Identifier),
            ("Core/Update/ReleaseManifestParser.cs", "В ответе нет номера версии", Log),
            ("Core/Update/ReleaseManifestParser.cs", "В релизе нет установщика x64 для версии ", Log),
            ("Core/Update/ReleaseManifestParser.cs", "Не удалось разобрать номер версии: ", Log),
            ("Core/Update/ReleaseManifestParser.cs", "Некорректный ответ: ", Log),
            ("Core/Update/ReleaseManifestParser.cs", "Пустой ответ сервера", Log),
            ("Core/Update/UnityWebRequestDownloader.cs", "Не удалось подготовить папку: ", Log),
            ("Core/Update/UnityWebRequestDownloader.cs", "загрузка встала: нет новых байтов {watchdog.Idle", Log),
        };

    public static readonly ISet<string> ComputesKeys = new HashSet<string>(StringComparer.Ordinal)
    {
        "Core/Pure/UI/HintText.cs",
        "Core/Pure/Localization/DecorNames.cs",
    };

    public static bool Allows(string file, string literal) =>
        Files.ContainsKey(file) || Literals.Any(e => e.file == file && literal.Contains(e.fragment));
}
