using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using KitchenServer.Web.Services;

namespace KitchenServer.Web.Endpoints;

/// <summary>
/// Browser-facing channel. The WebGL/desktop client opens a WebSocket to
/// /api/mcp/ws with the tab key generated by the editor page; the server attaches
/// it to that tab's session. Agent commands arrive over MCP (port 8081) and are
/// relayed here; the client's replies are matched back to pending requests by id.
/// </summary>
public static class McpEndpoints
{
    public static void MapMcpEndpoints(this WebApplication app)
    {
        app.Map("/api/mcp/ws", async (HttpContext context, McpSessionManager sessions) =>
        {
            if (!context.WebSockets.IsWebSocketRequest)
            {
                context.Response.StatusCode = 400;
                await context.Response.WriteAsync("WebSocket connection required");
                return;
            }

            var key = context.Request.Headers["X-MCP-Access-Key"].FirstOrDefault()
                      ?? context.Request.Query["key"].ToString();
            var session = sessions.GetByKey(key);
            if (session == null)
            {
                // Key must be pre-registered by the editor page for this tab.
                context.Response.StatusCode = 401;
                await context.Response.WriteAsync("Invalid or expired project key");
                return;
            }

            var ws = await context.WebSockets.AcceptWebSocketAsync();
            sessions.AttachBrowser(key, ws);

            var buffer = new byte[64 * 1024];
            var messageBuilder = new StringBuilder();
            try
            {
                while (ws.State == WebSocketState.Open)
                {
                    var result = await ws.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
                    if (result.MessageType == WebSocketMessageType.Close)
                    {
                        await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "", CancellationToken.None);
                        break;
                    }
                    if (result.MessageType != WebSocketMessageType.Text) continue;

                    messageBuilder.Append(Encoding.UTF8.GetString(buffer, 0, result.Count));
                    if (!result.EndOfMessage) continue;

                    var json = messageBuilder.ToString().Trim();
                    messageBuilder.Clear();
                    if (json.Length > 0) DispatchReply(session, json);
                }
            }
            catch (OperationCanceledException) { }
            catch (WebSocketException) { }
            finally
            {
                sessions.DetachBrowser(session);
                if (ws.State is WebSocketState.Open or WebSocketState.CloseReceived)
                {
                    try { await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "", CancellationToken.None); }
                    catch { }
                }
            }
        });
    }

    /// <summary>Match a client reply back to its pending MCP request by id.</summary>
    private static void DispatchReply(McpSession session, string json)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;
            if (root.ValueKind == JsonValueKind.Object && root.TryGetProperty("id", out var idProp))
            {
                var id = idProp.ValueKind == JsonValueKind.String ? idProp.GetString() : idProp.GetRawText();
                if (!string.IsNullOrEmpty(id))
                    session.ResolveResponse(id, root.Clone());
            }
        }
        catch (JsonException)
        {
            // Non-JSON / unexpected frame from the client — ignore.
        }
    }
}
