using System;
using System.Collections.Generic;

// The one authoritative list of MCP tools. Consumed by:
//   • Unity  — McpCommandHandler dispatches these method names (parity test guards it).
//   • Server — builds tools/list for real MCP over Streamable HTTP.
//   • Codegen — emits mcp-server/src/tools.generated.ts (Zod) for the local bridge.
// Keep this in sync with McpCommandHandler's switch (McpToolRegistryParityTests).
//
// SURFACE CONVENTION (2026-07): every element-addressing tool is a BATCH — it
// takes names[] / ops[] / items[]. There are NO single-element tools. All
// user-editable properties are changed through edit_elements.

namespace KitchenDesigner.Core.MCP.Contract
{
    public static class McpToolRegistry
    {
        public static readonly IReadOnlyList<McpToolDef> Tools = new List<McpToolDef>
        {
            // ── Meta / cheat-sheet (answered locally, no Unity call) ──────────────
            new McpToolDef("guide", "Guide / cheat-sheet",
                "Usage cheat-sheet. Topics: workflow (default; units, which tool to reach for, worked examples), planning (declarative floorplans: apply_floorplan/create_walls/create_floor/add_opening), bulk (selectors and set_attr/move/align/resize_module), elements (element types), fields (what each response field means), drawers (GTV drawers), violations (what counts as a violation). Call this first if unsure.",
                McpToolKind.Read, typeof(ParamsGuide), staticText: true),

            // ── Read: scene & elements ────────────────────────────────────────────
            new McpToolDef("ping", "Ping",
                "Check that Unity is reachable. Returns Unity version.",
                McpToolKind.Read, null),
            new McpToolDef("get_status", "Scene status",
                "Basic scene info: scene name, object count, play mode, platform.",
                McpToolKind.Read, null),
            new McpToolDef("get_all_elements", "List elements (legacy full dump)",
                "LEGACY, VERBOSE (~1 KB per element): every board/wall/floor with name, size (mm), position (m), rotation, AABB and hasViolations. Prefer get_scene_tree to look around and get/get_elements for the few names you actually need; call this only when a full dump is genuinely required.",
                McpToolKind.Read, null, cached: true),
            new McpToolDef("get_scene_tree", "Scene tree (compact)",
                "COMPACT hierarchy for 'looking around' cheaply (use this before the verbose get_all_elements): modules (named groups) with member names + world bbox, loose element names, and per-type counts. Then fetch details for a few names with get_elements.",
                McpToolKind.Read, null),
            new McpToolDef("get", "Get compact corner geometry",
                "Fetch exact names with selectable fields. Defaults to compact v2 geometry: name, kind, corner anchor in MM, size [width,depth,height] MM, rotY, violations and module. No verbose legacy fields.",
                McpToolKind.Read, typeof(ParamsGetCompact)),
            new McpToolDef("preview_floorplan", "Preview a floorplan declaration",
                "Validate a declarative floorplan without changing the scene and return a deterministic top-down SVG plus compact counts. Uses the exact same compiler as apply_floorplan.",
                McpToolKind.Read, typeof(ParamsFloorplanDeclaration)),
            new McpToolDef("apply_floorplan", "Apply a floorplan declaration",
                "Atomically create/update an entire compiled floorplan (rooms, shared walls, polygon floors, openings) in ONE undo step. Idempotent by declaration id; obsolete elements from that scope are deleted. Returns terse counts and violations.",
                McpToolKind.Write, typeof(ParamsFloorplanDeclaration)),
            new McpToolDef("get_elements", "Get elements (batch)",
                "Info for one or SEVERAL elements in ONE call: pick by exact names and/or a name filter (substring or wildcard '*'). summary:true returns compact one-line info per element; facade_validation:true adds facade opening diagnostics.",
                McpToolKind.Read, typeof(ParamsGetElements)),
            new McpToolDef("get_specification", "Specification",
                "Cut list: every distinct board size with count and area (m2), plus totals.",
                McpToolKind.Read, null),
            new McpToolDef("get_violations", "List violations",
                "List elements that overlap another (with severity and penetration depth in mm) or are disconnected from the wall/floor structure. Also returns issues[]: coded scene analysis (level=error|warning, code, detail, message, target, secondary). Errors COL-xx = collisions; warnings GAP-01 near-contact (<=8mm, not touching), SEAT-01 panel not fully seated in groove, FAC-01 facade gap <1mm, DRW-01 drawer without facade. Warnings are analysis-only (no scene highlight). Optional names[] limits the report to those boards. Note: every mutation already returns its own violations — call this to check the WHOLE scene.",
                McpToolKind.Read, typeof(ParamsGetViolations)),
            new McpToolDef("get_element_gaps", "Element gaps (batch)",
                "For EACH given board: gap or overlap (in mm) to the nearest neighbour on each axis X/Y/Z. Negative gapMM = overlap.",
                McpToolKind.Read, typeof(ParamsNames)),
            new McpToolDef("get_element_debug", "Element geometry (batch)",
                "Detailed geometry for EACH given element: AABB, face centers/normals, vertices, dims and effective dims (mm). For precise placement checks.",
                McpToolKind.Read, typeof(ParamsNames)),
            new McpToolDef("get_floor_info", "Floor info",
                "Size (mm) and position (m) of the floor plate (BasePlate).",
                McpToolKind.Read, null),
            new McpToolDef("get_settings", "Get settings",
                "Current project settings: snap on/off, snap threshold (mm), grid, autosave, verbose snap flag.",
                McpToolKind.Read, null),
            new McpToolDef("get_project_instructions", "Get project instructions",
                "Return the project's free-text agent instructions (conventions: wall thicknesses, board thickness, gaps...). Call after connecting.",
                McpToolKind.Read, null),
            new McpToolDef("set_project_instructions", "Set project instructions",
                "Replace the project's free-text agent instructions. Persists in the project file.",
                McpToolKind.Write, typeof(ParamsSetProjectInstructions)),

            // ── v2: массовые/реляционные операции (сервер считает геометрию) ──────
            new McpToolDef("set_attr", "Set attribute over a selection",
                "Bulk-change matched elements in ONE call by a selector: thickness/width/height/depth (MM), material, locked. Server picks the elements — you pass intent, not per-board numbers. Example: set_attr {selector:'all_boards thickness==18', thickness:16}. Undoable (geometry). Returns matched/updated/sceneViolationCount.",
                McpToolKind.Write, typeof(ParamsSetAttr)),
            new McpToolDef("move", "Move a selection by a delta",
                "Shift every matched element by (dx,dy,dz) MM in world axes. Locked elements are skipped. ONE undo step. Returns matched/updated/sceneViolationCount.",
                McpToolKind.Write, typeof(ParamsMove)),
            new McpToolDef("resize_module", "Resize a module by a delta",
                "Grow/shrink a module (named group) by delta MM along a world axis. The server keeps the near side fixed, moves the far side and stretches spanning boards — you pass (module, axis, delta), not 15 coordinates. ONE undo step. Returns matched/updated/sceneViolationCount.",
                McpToolKind.Write, typeof(ParamsResizeModule)),
            new McpToolDef("group", "Declare a module group",
                "Create/update an exact named group from element names and annotate its width axis. Idempotent by id; membership is replaced atomically in ONE undo step.",
                McpToolKind.Write, typeof(ParamsGroupV2)),
            new McpToolDef("align", "Align a selection relationally",
                "Move every matched loose element or whole matched module as a unit until its chosen face meets a target element/wall face with a gap in MM. Server computes all deltas; ONE undo step.",
                McpToolKind.Write, typeof(ParamsAlignSelection)),
            new McpToolDef("create_walls", "Create walls from corner coordinates",
                "Create/update a batch of bearing or partition walls from endpoint coordinates in MM. Geometry is derived server-side; thickness and optional material come from project instructions. Atomic, idempotent by segment name, ONE undo step.",
                McpToolKind.Write, typeof(ParamsCreateWalls)),
            new McpToolDef("create_floor", "Create a polygon floor",
                "Create/update a FloorElement from a simple polygon in MM. The top surface is corner-anchored; center/size/mesh are derived server-side. Atomic and idempotent by name, ONE undo step.",
                McpToolKind.Write, typeof(ParamsCreateFloorV2)),
            new McpToolDef("add_opening", "Add a wall opening",
                "Create/update a door or window by wall name, offset from its declared start, width/height/sill in MM. The server positions and attaches it and rebuilds the wall cutout. Atomic, idempotent by opening name, ONE undo step.",
                McpToolKind.Write, typeof(ParamsAddOpening)),
            new McpToolDef("snap_diagnose", "Diagnose snapping (batch)",
                "Explain why each given board does or does not snap to neighbours from its current (or a test) position: best face pair, gap vs threshold, overlap. x/y/z in METERS (optional, default = current position).",
                McpToolKind.Read, typeof(ParamsSnapDiagnose)),
            new McpToolDef("get_free_space", "Free space between two boards",
                "The empty box between two boards: size (mm), bounds (m), center, and any elements already inside it. Use BEFORE creating or resizing something to fit between panels — no manual AABB math.",
                McpToolKind.Read, typeof(ParamsGetFreeSpace)),

            // ── Edit elements (ALL batch, ALL atomic) ─────────────────────────────
            new McpToolDef("create_elements", "Create elements (batch)",
                "Create one or MANY elements in ONE call. Each item: unique name, type (board | wall | floor | facade | assembled_facade | radial_shelf | panel | drawer | table | radius_table | pillar | window | door, default board), x/y/z in METERS, width/height/depth in MILLIMETERS, plus type-specific fields (gaps, fill, drawer params, ...). panel = ДВП/ХДФ back panel whose gaps count toward its bounding box, so it seats into grooves. Atomic: if ANY item is invalid, NOTHING is created. Whole batch is ONE undo step. For architecture (walls, room floors, windows/doors) prefer the corner-anchored tools apply_floorplan / create_walls / create_floor / add_opening — they derive the geometry server-side instead of making you compute centers.",
                McpToolKind.Write, typeof(ParamsCreateElements)),
            new McpToolDef("edit_elements", "Edit element properties (batch)",
                "THE universal editor: change ANY user-editable properties of one or MANY elements in ONE transactional call. Each op: exact name + any of x/y/z (METERS), width/height/depth (MM), rot_x/rot_y/rot_z (DEGREES), locked, material, facade gap_left/right/top/bottom (MM), opening mode, assembled-facade fill, is_open, corner_radius, drawer params (drawer_type/drawer_length/drawer_color/internal_width/is_double/is_upper/paired_drawer_name/attached_facade_name), table leg_inset_mm/tabletop_material/legs_material, pillar mid_height_mm, window tint/sill_protrusion_mm, door sash_type. Type-specific fields are validated against the element's actual type. Atomic: if ANY op is invalid, NOTHING is applied. Geometry changes are ONE undo step. dry_run:true simulates (applies, reports per-op state + violations, reverts) — use it BEFORE risky moves/resizes.",
                McpToolKind.Write, typeof(ParamsEditElements)),
            new McpToolDef("convert_elements", "Convert element types (batch)",
                "Change the TYPE of one or MANY existing elements in place — board(part) <-> facade <-> assembled facade <-> radial shelf — keeping name, size, position and material. Atomic: if ANY op is invalid, NOTHING is converted. NOT undoable.",
                McpToolKind.Write, typeof(ParamsConvertElements)),
            new McpToolDef("clone_elements", "Clone elements (batch)",
                "For EACH op create COUNT copies of a board; copy N is shifted by N*offset (METERS) from the original. Copies are named <name>_2, <name>_3, … Whole batch is ONE undo step. Ideal for 'three identical shelves 300 mm apart'.",
                McpToolKind.Write, typeof(ParamsCloneElements)),
            new McpToolDef("align_elements", "Align face to face (batch)",
                "For EACH op move a board so its FACE sits flush against (or gap_mm away from) a TARGET board's face — no manual coordinate math. Ops are applied IN ORDER, so later ops see earlier moves (chain alignments!). Example op: {name:'Shelf1', face:'left', target:'Side_L', target_face:'right'}. Whole batch is ONE undo step. To align a whole SELECTION (e.g. every module against a wall) without naming boards, use align instead.",
                McpToolKind.Write, typeof(ParamsAlignElements)),
            new McpToolDef("distribute_evenly", "Distribute evenly",
                "Space 3+ boards evenly along a world axis: the two outermost stay, the middle ones move so center-to-center distances are equal. ONE undo step. Ideal for 'three shelves evenly between top and bottom'.",
                McpToolKind.Write, typeof(ParamsDistributeEvenly)),
            new McpToolDef("delete_elements", "Delete elements (batch)",
                "Delete one or MANY boards in ONE call. Atomic: if ANY element is missing or locked, NOTHING is deleted. Whole batch is ONE undo step.",
                McpToolKind.Destructive, typeof(ParamsNames)),
            new McpToolDef("select_elements", "Select elements (batch)",
                "Select and highlight one or MANY boards in the app (visual only, no geometry change).",
                McpToolKind.Write, typeof(ParamsNames)),
            new McpToolDef("cycle_drawer_animation", "Open / close drawers (batch)",
                "Animate GTV drawers: a single drawer toggles open/closed; a double drawer cycles Closed -> BothOpen -> LowerOnly -> Closed (its paired drawer and attached facades move in sync). Returns isOpen and doubleState per drawer.",
                McpToolKind.Write, typeof(ParamsNames)),
            new McpToolDef("list_materials", "List materials / textures",
                "List the available material decors / textures (id, display name, kind, whether it has a texture, and its physical tile size in MM). Use before edit_elements {material} to pick a valid id.",
                McpToolKind.Read, null),
            new McpToolDef("reload_textures", "Reload external textures",
                "Re-scan the external textures folder (<app>/Resources/Textures) and refresh the decor catalog WITHOUT restarting the app. Drop new image files there (named '<name>_<widthMM>_<heightMM>.jpg' to set tile size), then call this. Returns how many were loaded and the folder path.",
                McpToolKind.Write, null),
            new McpToolDef("resize_floor", "Resize floor (legacy singleton)",
                "LEGACY: set the size of the scene's single BasePlate floor plate in MILLIMETERS. Real rooms use polygon floors — prefer create_floor / apply_floorplan. Undoable.",
                McpToolKind.Write, typeof(ParamsResizeFloor)),

            // ── Modules (named groups of boards) ──────────────────────────────────
            new McpToolDef("get_modules", "List modules",
                "List all modules (named groups) with their member boards and bounding box.",
                McpToolKind.Read, null),
            new McpToolDef("module_info", "Module info (batch)",
                "Full configuration of one or MANY modules: members, bounds, edit state.",
                McpToolKind.Read, typeof(ParamsModules)),
            new McpToolDef("create_module", "Create module",
                "Group two or more boards into a named module (they then move together). To declare membership idempotently and annotate the width axis used by resize_module, use group instead.",
                McpToolKind.Write, typeof(ParamsCreateModule)),
            new McpToolDef("dissolve_module", "Dissolve modules (batch)",
                "Ungroup one or MANY modules. The boards stay in the scene.",
                McpToolKind.Destructive, typeof(ParamsModules)),
            new McpToolDef("add_to_module", "Add to module (batch)",
                "Add one or MANY boards to an existing module.",
                McpToolKind.Write, typeof(ParamsModuleElements)),
            new McpToolDef("remove_from_module", "Remove from module (batch)",
                "Remove one or MANY boards from their modules.",
                McpToolKind.Write, typeof(ParamsNames)),
            new McpToolDef("enter_module_edit", "Enter module edit",
                "Enter module edit mode (a single module at a time): only that module's boards are editable, the rest of the scene is locked/dimmed.",
                McpToolKind.Write, typeof(ParamsModule)),
            new McpToolDef("exit_module_edit", "Exit module edit",
                "Leave module edit mode.",
                McpToolKind.Write, null),

            // ── Settings / diagnostics / export ───────────────────────────────────
            new McpToolDef("set_setting", "Change a setting",
                "Toggle one boolean project setting. name is one of: lower_near_walls | snap_enabled | grid_enabled | walls_enabled | camera_pan_free.",
                McpToolKind.Write, typeof(ParamsSetSetting)),
            new McpToolDef("set_snap_verbose", "Verbose snap log",
                "Turn detailed snap logging in the Unity console on or off (debugging).",
                McpToolKind.Write, typeof(ParamsSetEnabled)),
            new McpToolDef("get_console_logs", "Console logs",
                "Recent Unity console log entries (for debugging).",
                McpToolKind.Read, typeof(ParamsLogCount)),
            new McpToolDef("export_specification_csv", "Export CSV",
                "Export the specification (cut list) to a CSV file on disk.",
                McpToolKind.Write, typeof(ParamsExportCsv)),
            new McpToolDef("take_screenshot", "Screenshot",
                "Capture a screenshot of the app; returns the saved PNG file path.",
                McpToolKind.Read, null),

            // ── Advanced: raw Unity objects (no undo / no validation) ─────────────
            new McpToolDef("find_objects", "Find objects (advanced)",
                "ADVANCED. Find GameObjects by partial name. For kitchen boards prefer get_all_elements.",
                McpToolKind.Read, typeof(ParamsFindObjects)),
            new McpToolDef("get_object_info", "Object info (advanced, batch)",
                "ADVANCED. Raw GameObject info (transform, components, children) for EACH given path. For boards prefer get_elements.",
                McpToolKind.Read, typeof(ParamsObjectPaths)),
            new McpToolDef("get_scene_hierarchy", "Scene hierarchy (advanced)",
                "ADVANCED. Full GameObject hierarchy of the scene.",
                McpToolKind.Read, null),
            new McpToolDef("set_object_active", "Show/hide objects (advanced, batch)",
                "ADVANCED. Enable or disable raw GameObjects.",
                McpToolKind.Write, typeof(ParamsSetActiveOps)),
            new McpToolDef("delete_object", "Delete objects (advanced, batch)",
                "ADVANCED. Destroy raw GameObjects with NO undo. For boards prefer delete_elements (undoable).",
                McpToolKind.Destructive, typeof(ParamsObjectPaths)),
            new McpToolDef("set_position", "Set positions (advanced, batch)",
                "ADVANCED. Set raw GameObject world positions in METERS, with NO undo/validation/snap. x/y/z are OPTIONAL — omit an axis to keep its current value. For boards prefer edit_elements.",
                McpToolKind.Write, typeof(ParamsTransformOps)),
            new McpToolDef("set_rotation", "Set rotations (advanced, batch)",
                "ADVANCED. Set raw GameObject rotations (Euler DEGREES), no undo. x/y/z are OPTIONAL — omit an axis to keep its current value. For boards prefer edit_elements.",
                McpToolKind.Write, typeof(ParamsTransformOps)),
            new McpToolDef("set_scale", "Set scales (advanced, batch)",
                "ADVANCED and RISKY. Sets raw Transform scales — this does NOT change a board's mm size and can distort meshes. To change a board size use edit_elements instead.",
                McpToolKind.Write, typeof(ParamsTransformOps)),
            new McpToolDef("execute_menu_item", "Run editor menu (advanced)",
                "ADVANCED (Editor only). Execute a Unity Editor menu command by path, e.g. 'Edit/Undo'.",
                McpToolKind.Write, typeof(ParamsMenuPath), openWorld: true),
            new McpToolDef("enter_play_mode", "Enter play mode (advanced)",
                "ADVANCED (Editor only). Enter Unity Play Mode.",
                McpToolKind.Write, null),
            new McpToolDef("exit_play_mode", "Exit play mode (advanced)",
                "ADVANCED (Editor only). Exit Unity Play Mode.",
                McpToolKind.Write, null),
        };

        /// <summary>Method names in the registry (excludes staticText-only tools like guide).</summary>
        public static IEnumerable<string> UnityMethodNames()
        {
            foreach (var t in Tools)
                if (!t.StaticText)
                    yield return t.Name;
        }
    }
}
