using System;
using System.Collections.Generic;

// The one authoritative list of MCP tools. Consumed by:
//   • Unity  — McpCommandHandler dispatches these method names (parity test guards it).
//   • Server — builds tools/list for real MCP over Streamable HTTP.
//   • Codegen — emits mcp-server/src/tools.generated.ts (Zod) for the local bridge.
// Keep this in sync with McpCommandHandler's switch (McpToolRegistryParityTests).

namespace KitchenDesigner.Core.MCP.Contract
{
    public static class McpToolRegistry
    {
        public static readonly IReadOnlyList<McpToolDef> Tools = new List<McpToolDef>
        {
            // ── Meta / cheat-sheet (answered locally, no Unity call) ──────────────
            new McpToolDef("guide", "Guide / cheat-sheet",
                "Usage cheat-sheet. Topics: workflow (default; units, batch editing, worked examples), elements (element types), fields (what each response field means), drawers (GTV drawers), violations (what counts as a violation). Call this first if unsure.",
                McpToolKind.Read, typeof(ParamsGuide), staticText: true),

            // ── Read: scene & elements ────────────────────────────────────────────
            new McpToolDef("ping", "Ping",
                "Check that Unity is reachable. Returns Unity version.",
                McpToolKind.Read, null),
            new McpToolDef("get_status", "Scene status",
                "Basic scene info: scene name, object count, play mode, platform.",
                McpToolKind.Read, null),
            new McpToolDef("get_all_elements", "List elements",
                "List ALL boards/walls/floor with name, size (mm), position (m), rotation, AABB and hasViolations. Call this FIRST before editing.",
                McpToolKind.Read, null, cached: true),
            new McpToolDef("get_element_info", "Element info",
                "Full info for one element by name: size (mm), position (m), rotation, module, hasViolations, AABB.",
                McpToolKind.Read, typeof(ParamsName)),
            new McpToolDef("get_elements", "Get elements (batch)",
                "Info for SEVERAL elements in ONE call: pick by exact names and/or a name filter (substring or wildcard '*'). summary:true returns compact one-line info per element. Prefer this over repeated get_element_info calls.",
                McpToolKind.Read, typeof(ParamsGetElements)),
            new McpToolDef("get_specification", "Specification",
                "Cut list: every distinct board size with count and area (m2), plus totals.",
                McpToolKind.Read, null),
            new McpToolDef("get_violations", "List violations",
                "List elements that overlap another (with severity and penetration depth in mm) or are disconnected from the wall/floor structure. Optional names[] limits the report to those boards. Note: every mutation already returns its own violations — call this to check the WHOLE scene.",
                McpToolKind.Read, typeof(ParamsGetViolations)),
            new McpToolDef("get_element_gaps", "Element gaps",
                "Gap or overlap (in mm) to the nearest neighbour on each axis X/Y/Z. Negative gapMM = overlap.",
                McpToolKind.Read, typeof(ParamsName)),
            new McpToolDef("get_element_debug", "Element geometry",
                "Detailed geometry of one element: AABB, face centers/normals, vertices, dims and effective dims (mm). For precise placement checks.",
                McpToolKind.Read, typeof(ParamsName)),
            new McpToolDef("get_floor_info", "Floor info",
                "Size (mm) and position (m) of the floor plate (BasePlate).",
                McpToolKind.Read, null),
            new McpToolDef("get_settings", "Get settings",
                "Current project settings: snap on/off, snap threshold (mm), grid, autosave, verbose snap flag.",
                McpToolKind.Read, null),

            // ── Check (dry-run) ───────────────────────────────────────────────────
            new McpToolDef("simulate_move", "Simulate move (dry-run)",
                "DRY-RUN of a move: does NOT move anything. Returns simulatedAABB, overlapsWith and wouldHaveViolations. Call BEFORE move_element. x/y/z in METERS. Each axis is OPTIONAL — omit an axis to keep the board's current value on it (a missing axis is NOT treated as 0).",
                McpToolKind.Read, typeof(ParamsSimulateMove)),
            new McpToolDef("simulate_resize", "Simulate resize (dry-run)",
                "DRY-RUN of a resize: does NOT change size. Returns simulatedAABB, overlapsWith and wouldHaveViolations. Call BEFORE resize_element. width/height/depth in MILLIMETERS. Each is OPTIONAL — omit a dimension to keep the board's current size on it (a missing dimension is NOT treated as 0).",
                McpToolKind.Read, typeof(ParamsSimulateResize)),
            new McpToolDef("snap_diagnose", "Diagnose snapping",
                "Explain why a board does or does not snap to neighbours from its current (or a test) position: best face pair, gap vs threshold, overlap. x/y/z in METERS (optional, default = current position).",
                McpToolKind.Read, typeof(ParamsSnapDiagnose)),

            // ── Edit elements ─────────────────────────────────────────────────────
            new McpToolDef("create_element", "Create element",
                "Create a new board (default), or a wall / facade / assembled facade / floor / table. x/y/z in METERS; width/height/depth in MILLIMETERS (defaults 800x400x18, assembled default 450x700x18, table default 1200x750x600). Set is_wall/is_facade/is_assembled/is_floor/is_table for other kinds. Prefer this over raw Unity object creation.",
                McpToolKind.Write, typeof(ParamsCreateElement)),
            new McpToolDef("convert_element", "Convert element type",
                "Change the TYPE of an existing element in place — board(part) <-> facade <-> assembled facade — keeping its name, size, position and material. Use this to turn a regular facade into an assembled (framed) one, or vice versa. NOT undoable.",
                McpToolKind.Write, typeof(ParamsConvertElement)),
            new McpToolDef("batch_edit", "Batch edit (one undo step)",
                "Apply MANY changes in ONE transactional call. Each op: exact name + any of x/y/z (METERS), width/height/depth (MM), rot_x/rot_y/rot_z (DEGREES), locked, material — all given fields apply together. Atomic: if ANY op is invalid, NOTHING is applied. Undo reverts the whole batch. dry_run:true simulates, reports per-op violations and reverts. PREFER this over a series of move/resize/rotate calls.",
                McpToolKind.Write, typeof(ParamsBatchEdit)),
            new McpToolDef("clone_element", "Clone element",
                "Create COUNT copies of a board; copy N is shifted by N*offset (METERS) from the original. Copies are named <name>_2, <name>_3, … Whole clone is ONE undo step. Ideal for 'three identical shelves 300 mm apart'.",
                McpToolKind.Write, typeof(ParamsCloneElement)),
            new McpToolDef("move_element", "Move element",
                "Move a board to an absolute position. Undoable, validated, snaps to neighbours. x/y/z in METERS. Each axis is OPTIONAL — omit an axis to keep the board's current value on it (a missing axis is NOT treated as 0), so you can move on one axis only. Fails if the element is locked. Run simulate_move first.",
                McpToolKind.Write, typeof(ParamsMoveElement)),
            new McpToolDef("resize_element", "Resize element",
                "Set a board's size in MILLIMETERS. Undoable and validated. depth is the thickness (Z). Each dimension is OPTIONAL — omit one to keep the board's current size on it (a missing dimension is NOT treated as 0), so you can change one dimension only. Fails if locked. Run simulate_resize first.",
                McpToolKind.Write, typeof(ParamsResizeElement)),
            new McpToolDef("rotate_element", "Rotate element",
                "Set a board's rotation as Euler angles in DEGREES. Undoable. Common: rotate (0,90,0) to swap width and thickness. Each axis is OPTIONAL — omit an axis to keep the board's current angle on it (a missing axis is NOT treated as 0). Fails if locked.",
                McpToolKind.Write, typeof(ParamsRotateElement)),
            new McpToolDef("align_element", "Align face to face",
                "Move a board so its FACE sits flush against (or gap_mm away from) a TARGET board's face — no manual coordinate math. Example: {name:'Shelf1', face:'left', target:'Side_L', target_face:'right'} presses the shelf against the panel. Undoable; returns the same envelope as move_element.",
                McpToolKind.Write, typeof(ParamsAlignElement)),
            new McpToolDef("distribute_evenly", "Distribute evenly",
                "Space 3+ boards evenly along a world axis: the two outermost stay, the middle ones move so center-to-center distances are equal. ONE undo step. Ideal for 'three shelves evenly between top and bottom'.",
                McpToolKind.Write, typeof(ParamsDistributeEvenly)),
            new McpToolDef("get_free_space", "Free space between two boards",
                "The empty box between two boards: size (mm), bounds (m), center, and any elements already inside it. Use BEFORE creating or resizing something to fit between panels — no manual AABB math.",
                McpToolKind.Read, typeof(ParamsGetFreeSpace)),
            new McpToolDef("delete_element", "Delete element",
                "Delete a board. Undoable with undo. Fails if the element is locked.",
                McpToolKind.Destructive, typeof(ParamsName)),
            new McpToolDef("select_element", "Select element",
                "Select and highlight a board in the app (visual only, no geometry change).",
                McpToolKind.Write, typeof(ParamsName)),
            new McpToolDef("set_element_lock", "Lock / unlock element",
                "Lock or unlock a board. Locked boards cannot be moved/resized/deleted. Set locked:false ONLY with the user's explicit permission.",
                McpToolKind.Write, typeof(ParamsElementLock)),
            new McpToolDef("set_facade_mode", "Facade open mode",
                "Change how a facade element opens: hinge (door swinging around one edge) or drawer (sliding along a face). 18 modes. Fails if the element is not a facade.",
                McpToolKind.Write, typeof(ParamsSetFacadeMode)),
            new McpToolDef("set_drawer_properties", "Set drawer properties",
                "Change a GTV drawer's parameters: type (A/B/C/D side height), nominal length, color, internal width, double-drawer pairing and attached facade. Every field is optional — omit to keep current. Fails if the element is not a drawer. Use this instead of resize_element for drawers.",
                McpToolKind.Write, typeof(ParamsSetDrawerProperties)),
            new McpToolDef("set_radial_shelf_properties", "Set radial shelf properties",
                "Change a radial shelf's corner rounding radius in MM (clamped to 1..min(width, depth)). Board size is changed via resize_element. Fails if the element is not a radial shelf.",
                McpToolKind.Write, typeof(ParamsSetRadialShelfProperties)),
			new McpToolDef("set_table_properties", "Set table properties",
				"Change a table's parameters: leg inward offset from corners along X and Z axes, in MM. Every field is optional — omit to keep current. Fails if the element is not a table.",
				McpToolKind.Write, typeof(ParamsSetTableProperties)),
			new McpToolDef("set_pillar_properties", "Pillar properties",
				"Change a pillar's middle cylinder height in MM (clamped 50..100). Fails if the element is not a pillar.",
				McpToolKind.Write, typeof(ParamsSetPillarProperties)),
            new McpToolDef("set_window_properties", "Set window properties",
                "Change a window element's parameters: glass tint (clear/tinted), windowsill protrusion (0..200 mm), opening mode, and open/close state. Every field is optional — omit to keep current. Fails if the element is not a window.",
                McpToolKind.Write, typeof(ParamsSetWindowProperties)),
            new McpToolDef("set_door_properties", "Set door properties",
                "Change a door element's parameters: sash type (glass/blind), opening mode, and open/close state. Every field is optional — omit to keep current. Fails if the element is not a door.",
                McpToolKind.Write, typeof(ParamsSetDoorProperties)),
			new McpToolDef("cycle_drawer_animation", "Open / close drawer",
                "Animate a GTV drawer: a single drawer toggles open/closed; a double drawer cycles Closed -> BothOpen -> LowerOnly -> Closed (its paired drawer and attached facades move in sync). Returns isOpen and doubleState.",
                McpToolKind.Write, typeof(ParamsName)),
            new McpToolDef("list_materials", "List materials / textures",
                "List the available material decors / textures (id, display name, kind, whether it has a texture, and its physical tile size in MM). Use before set_material to pick a valid id.",
                McpToolKind.Read, null),
            new McpToolDef("set_material", "Set material / texture",
                "Assign a material decor / texture to a board or facade. When a non-default decor is set, the object shows that texture instead of the flat validation tint. Undoable via re-set; call list_materials first for valid ids.",
                McpToolKind.Write, typeof(ParamsSetMaterial)),
            new McpToolDef("reload_textures", "Reload external textures",
                "Re-scan the external textures folder (<app>/Resources/Textures) and refresh the decor catalog WITHOUT restarting the app. Drop new image files there (named '<name>_<widthMM>_<heightMM>.jpg' to set tile size), then call this. Returns how many were loaded and the folder path.",
                McpToolKind.Write, null),
            new McpToolDef("add_wall_component", "Make element a wall",
                "Turn an existing board into a wall (structural anchor). No-op if it is already a wall.",
                McpToolKind.Write, typeof(ParamsName)),
            new McpToolDef("resize_floor", "Resize floor",
                "Set the floor plate size in MILLIMETERS. Undoable.",
                McpToolKind.Write, typeof(ParamsResizeFloor)),

            // ── Undo / redo ───────────────────────────────────────────────────────
            new McpToolDef("undo", "Undo",
                "Undo the last edit. Returns ok:false if there is nothing to undo.",
                McpToolKind.Write, null),
            new McpToolDef("redo", "Redo",
                "Redo the last undone edit.",
                McpToolKind.Write, null),
            new McpToolDef("get_undo_stack_info", "Undo stack info",
                "Whether undo/redo are available and a description of the next undo.",
                McpToolKind.Read, null),

            // ── Modules (named groups of boards) ──────────────────────────────────
            new McpToolDef("get_modules", "List modules",
                "List all modules (named groups) with their member boards and bounding box.",
                McpToolKind.Read, null),
            new McpToolDef("module_info", "Module info",
                "Full configuration of one module: members, bounds, edit state.",
                McpToolKind.Read, typeof(ParamsModule)),
            new McpToolDef("create_module", "Create module",
                "Group two or more boards into a named module (they then move together).",
                McpToolKind.Write, typeof(ParamsCreateModule)),
            new McpToolDef("dissolve_module", "Dissolve module",
                "Ungroup a module. The boards stay in the scene.",
                McpToolKind.Destructive, typeof(ParamsModule)),
            new McpToolDef("add_to_module", "Add to module",
                "Add one board to an existing module.",
                McpToolKind.Write, typeof(ParamsModuleElement)),
            new McpToolDef("remove_from_module", "Remove from module",
                "Remove one board from its module.",
                McpToolKind.Write, typeof(ParamsName)),
            new McpToolDef("enter_module_edit", "Enter module edit",
                "Enter module edit mode: only that module's boards are editable, the rest of the scene is locked/dimmed.",
                McpToolKind.Write, typeof(ParamsModule)),
            new McpToolDef("exit_module_edit", "Exit module edit",
                "Leave module edit mode.",
                McpToolKind.Write, null),

            // ── Settings / diagnostics / export ───────────────────────────────────
            new McpToolDef("set_setting", "Change a setting",
                "Toggle one boolean project setting. name is one of: lower_near_walls | snap_enabled | grid_enabled | walls_enabled.",
                McpToolKind.Write, typeof(ParamsSetSetting)),
            new McpToolDef("set_snap_verbose", "Verbose snap log",
                "Turn detailed snap logging in the Unity console on or off (debugging).",
                McpToolKind.Write, typeof(ParamsSetEnabled)),
            new McpToolDef("get_console_logs", "Console logs",
                "Recent Unity console log entries (for debugging).",
                McpToolKind.Read, typeof(ParamsLogCount)),
            new McpToolDef("export_specification_csv", "Export CSV",
                "Export the specification (cut list) to a CSV file on disk.",
                McpToolKind.Write, typeof(ParamsExportCsv)),
            new McpToolDef("take_screenshot", "Screenshot",
                "Capture a screenshot of the app; returns the saved PNG file path.",
                McpToolKind.Read, null),

            // ── Advanced: raw Unity objects (no undo / no validation) ─────────────
            new McpToolDef("find_objects", "Find objects (advanced)",
                "ADVANCED. Find GameObjects by partial name. For kitchen boards prefer get_all_elements.",
                McpToolKind.Read, typeof(ParamsFindObjects)),
            new McpToolDef("get_object_info", "Object info (advanced)",
                "ADVANCED. Raw GameObject info (transform, components, children). For boards prefer get_element_info.",
                McpToolKind.Read, typeof(ParamsObjectPath)),
            new McpToolDef("get_scene_hierarchy", "Scene hierarchy (advanced)",
                "ADVANCED. Full GameObject hierarchy of the scene.",
                McpToolKind.Read, null),
            new McpToolDef("set_object_active", "Show/hide object (advanced)",
                "ADVANCED. Enable or disable a raw GameObject.",
                McpToolKind.Write, typeof(ParamsSetActive)),
            new McpToolDef("delete_object", "Delete object (advanced)",
                "ADVANCED. Destroy a raw GameObject with NO undo. For boards prefer delete_element (undoable).",
                McpToolKind.Destructive, typeof(ParamsObjectPath)),
            new McpToolDef("set_position", "Set position (advanced)",
                "ADVANCED. Set a raw GameObject world position in METERS, with NO undo/validation/snap. x/y/z are OPTIONAL — omit an axis to keep its current value. For boards prefer move_element.",
                McpToolKind.Write, typeof(ParamsSetTransform)),
            new McpToolDef("set_rotation", "Set rotation (advanced)",
                "ADVANCED. Set a raw GameObject rotation (Euler DEGREES), no undo. x/y/z are OPTIONAL — omit an axis to keep its current value. For boards prefer rotate_element.",
                McpToolKind.Write, typeof(ParamsSetTransform)),
            new McpToolDef("set_scale", "Set scale (advanced)",
                "ADVANCED and RISKY. Sets raw Transform scale — this does NOT change a board's mm size and can distort meshes. To change a board size use resize_element instead.",
                McpToolKind.Write, typeof(ParamsSetTransform)),
            new McpToolDef("execute_menu_item", "Run editor menu (advanced)",
                "ADVANCED (Editor only). Execute a Unity Editor menu command by path, e.g. 'Edit/Undo'.",
                McpToolKind.Write, typeof(ParamsMenuPath), openWorld: true),
            new McpToolDef("enter_play_mode", "Enter play mode (advanced)",
                "ADVANCED (Editor only). Enter Unity Play Mode.",
                McpToolKind.Write, null),
            new McpToolDef("exit_play_mode", "Exit play mode (advanced)",
                "ADVANCED (Editor only). Exit Unity Play Mode.",
                McpToolKind.Write, null),
        };

        /// <summary>Method names in the registry (excludes staticText-only tools like guide).</summary>
        public static IEnumerable<string> UnityMethodNames()
        {
            foreach (var t in Tools)
                if (!t.StaticText)
                    yield return t.Name;
        }
    }
}
